image: ubuntu:20.04
stages:
  - test

before_script:
  - apt-get update -qy
  - apt-get install -y curl
  - apt-get install -y ca-certificates gnupg
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  - NODE_MAJOR=18 echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
  - apt-get update -y
  - apt-get install -y nodejs

test:
  stage: test
  script:
    - npm install
    - npm install -g ganache
    - npm install -g truffle
    - ganache-cli > /dev/null 2>&1 &
    #- truffle migrate && truffle test --f $(truffle latest | grep -oE '[0-9]+') --t $(truffle latest | grep -oE '[0-9]+')
    - truffle migrate && truffle test "./test/giteta.js" "./test/gitarg.js" "./test/gitar.js" "./test/repo.js" "./test/ratig.js" "./test/type.js" "./test/Commit.js" "./test/Handshakes.js"  
    # issue: the structure of the command must have been played a 100 bijillion times in cache or just a parse error in code
    #&& truffle test ./test/argctl.js
    #- truffle test test/argctl.js